//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/* Date: Jan 30, 2020
 * Author: Brian Appleton
 * 
 * Thread Project #2
 * 
 * class for product model
 *
 */

namespace WebAPP
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Products_Suppliers = new HashSet<Products_Suppliers>();
        }
    
        public int ProductId { get; set; }

        [Display(Name = "Product")]
        public string ProdName { get; set; }


        public string ImagePath
        {
            get
            {
                switch (ProductId)
                {
                    case 1:
                        return "plane.jpg";
                    case 2:
                        return "attraction.jpg";
                    case 3:
                        return "car.jpg";
                    case 4:
                        return "cruise.jpg";
                    case 5:
                        return "hotel.jpg";
                    case 6:
                        return "coach.jpg";
                    case 7:
                        return "railroad.jpg";
                    case 8:
                        return "tour.png";
                    case 9:
                        return "insurance.jpg";
                    case 10:
                        return "boat.jpg";
                    default:
                        return "product.png";

                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_Suppliers> Products_Suppliers { get; set; }
    }
}
